import type { States } from "../../../context/types";

export const formData: States = {
    "codigoFipe": "004362-1",
    "marca": "GM - Chevrolet",
    "modelo": "AGILE LT 1.4 MPFI 8V FlexPower 5p",
    "anoModelo": 2025,
    "cpf": "288.983.080-27",
    "nome": "Douglas Silva",
    "email": "sgidin@artesp.sp.gov",
    "telefone": "(19) 99970-544",
    "valor": 4000,
    "numeroCotacao": "",
    "status": "",
    "validade": "",
    "formaPagamento": "Cartão",
    "quantidadeParcelas": 12,
    "endereco": "Rua Professora Maria Arruda Pacheco",
    "numeroProposta": "",
    "pdfPropostaBase64": "",
    "protocolo": null,
    "codMsgRet": null,
    "textoMsgRet": null,
    "cod_fipe": "004362-1",
    "num_passageiros": 5,
    "cod_marca": "266",
    "cod_modelo": "1243000",
    "cod_categoria_suhai": 1,
    "categoria_suhai": "Automóvel",
    "cod_categoria_tarifaria": "10",
    "cpfCnpj": "288.983.080-27",
    "cpfCnpjPrincipalCondutor": "288.983.080-27",
    "nomePrincipalCondutor": "Douglas Silva",
    "zeroKm": "N",
    "tipoUtilizacao": "1",
    "possuiOutroVeic": "0",
    "estadoCivil": "1",
    "sexoPrincipalCondutor": "2",
    "estadoCivilPrincipalCondutor": "1",
    "pergunta1": "1",
    "pergunta2": "1",
    "pergunta4": "1",
    "pergunta3": "1",
    "tipoContratacao": "1",
    "sexo": "2"
}